- name: restart prosody
  systemd:
    name: prosody
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: restart coturn
  systemd:
    name: coturn
    daemon_reload: yes
    enabled: yes
    state: restarted
